# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainscreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QTimer, QTime, QDate, Qt,QDateTime

class Ui_Mainscreen(object):
    def setupUi(self, Mainscreen):
        Mainscreen.setObjectName("Mainscreen")
        Mainscreen.resize(1000, 600)
        self.centralwidget = QtWidgets.QWidget(Mainscreen)
        self.centralwidget.setObjectName("centralwidget")
        self.bg = QtWidgets.QLabel(self.centralwidget)
        self.bg.setGeometry(QtCore.QRect(0, 0, 1000, 600))
        self.bg.setStyleSheet("\n"
"background: url(:/ui/main_bg.jpeg)  no-repeat center center fixed;")
        self.bg.setText("")
        self.bg.setAlignment(QtCore.Qt.AlignCenter)
        self.bg.setObjectName("bg")
        self.registeration_icon = QtWidgets.QLabel(self.centralwidget)
        self.registeration_icon.setGeometry(QtCore.QRect(80, 300, 200, 200))
        self.registeration_icon.setStyleSheet("image: url(:/ui/reg_icon.png);")
        self.registeration_icon.setText("")
        self.registeration_icon.setAlignment(QtCore.Qt.AlignCenter)
        self.registeration_icon.setObjectName("registeration_icon")
        self.attendance_icon = QtWidgets.QLabel(self.centralwidget)
        self.attendance_icon.setGeometry(QtCore.QRect(380, 300, 200, 200))
        self.attendance_icon.setStyleSheet("image: url(:/ui/attendance_icon.png);")
        self.attendance_icon.setText("")
        self.attendance_icon.setAlignment(QtCore.Qt.AlignCenter)
        self.attendance_icon.setObjectName("attendance_icon")
        self.show_att_icon = QtWidgets.QLabel(self.centralwidget)
        self.show_att_icon.setGeometry(QtCore.QRect(693, 300, 200, 200))
        self.show_att_icon.setStyleSheet("image: url(:/ui/showatt_icon.png);")
        self.show_att_icon.setText("")
        self.show_att_icon.setAlignment(QtCore.Qt.AlignCenter)
        self.show_att_icon.setObjectName("show_att_icon")
        self.date = QtWidgets.QLabel(self.centralwidget)
        self.date.setGeometry(QtCore.QRect(310, 170, 350, 50))
        self.date.setStyleSheet("color: rgb(255, 255, 0);\n"
"font: 70 24pt \"Tahoma\";")
        self.date.setAlignment(QtCore.Qt.AlignCenter)
        self.date.setObjectName("date")
        self.Time = QtWidgets.QLabel(self.centralwidget)
        self.Time.setGeometry(QtCore.QRect(310, 230, 350, 50))
        self.Time.setStyleSheet("color: rgb(255, 255, 0);\n"
"font: 70 24pt \"Tahoma\";")
        self.Time.setAlignment(QtCore.Qt.AlignCenter)
        self.Time.setObjectName("Time")
        self.Register = QtWidgets.QPushButton(self.centralwidget)
        self.Register.setGeometry(QtCore.QRect(80, 520, 200, 45))
        self.Register.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Register.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(170, 255, 255);\n"
"    font: 75 18pt \"Times New Roman\";\n"
"    border-radius: 12px;\n"
"}\n"
"QPushButton:hover\n"
"{font: 75 20pt \"Times New Roman\";\n"
"    background-color: rgb(75, 225, 225);\n"
"}\n"
"QPushButton:pressed \n"
"{\n"
"    background-color: rgb(52, 143, 255);\n"
"}")
        self.Register.setObjectName("Register")
        self.Take_attendance = QtWidgets.QPushButton(self.centralwidget)
        self.Take_attendance.setGeometry(QtCore.QRect(380, 520, 200, 45))
        self.Take_attendance.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Take_attendance.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(170, 255, 255);\n"
"    font: 75 18pt \"Times New Roman\";\n"
"    border-radius: 12px;\n"
"}\n"
"QPushButton:hover\n"
"{font: 75 20pt \"Times New Roman\";\n"
"    background-color: rgb(75, 225, 225);\n"
"}\n"
"QPushButton:pressed \n"
"{\n"
"    background-color: rgb(52, 143, 255);\n"
"}")
        self.Take_attendance.setObjectName("Take_attendance")
        self.view_attendance = QtWidgets.QPushButton(self.centralwidget)
        self.view_attendance.setGeometry(QtCore.QRect(693, 520, 200, 45))
        self.view_attendance.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.view_attendance.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(170, 255, 255);\n"
"    font: 75 18pt \"Times New Roman\";\n"
"    border-radius: 12px;\n"
"}\n"
"QPushButton:hover\n"
"{font: 75 20pt \"Times New Roman\";\n"
"    background-color: rgb(75, 225, 225);\n"
"}\n"
"QPushButton:pressed \n"
"{\n"
"    background-color: rgb(52, 143, 255);\n"
"}")
        self.view_attendance.setObjectName("view_attendance")
        self.Title_fr = QtWidgets.QLabel(self.centralwidget)
        self.Title_fr.setGeometry(QtCore.QRect(150, 10, 700, 90))
        self.Title_fr.setStyleSheet("image: url(:/ui/FR.png);")
        self.Title_fr.setText("")
        self.Title_fr.setAlignment(QtCore.Qt.AlignCenter)
        self.Title_fr.setObjectName("Title_fr")
        self.Title_as = QtWidgets.QLabel(self.centralwidget)
        self.Title_as.setGeometry(QtCore.QRect(100, 80, 800, 90))
        self.Title_as.setStyleSheet("image: url(:/ui/AS.png);")
        self.Title_as.setText("")
        self.Title_as.setAlignment(QtCore.Qt.AlignCenter)
        self.Title_as.setObjectName("Title_as")
        self.about = QtWidgets.QLabel(self.centralwidget)
        self.about.setGeometry(QtCore.QRect(935, 540, 41, 41))
        self.about.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.about.setStyleSheet("image: url(:/ui/about.png);")
        self.about.setText("")
        self.about.setObjectName("about")
        Mainscreen.setCentralWidget(self.centralwidget)

        self.retranslateUi(Mainscreen)
        QtCore.QMetaObject.connectSlotsByName(Mainscreen)

    def retranslateUi(self, Mainscreen):
        _translate = QtCore.QCoreApplication.translate
        Mainscreen.setWindowTitle(_translate("Mainscreen", "MainWindow"))
        current_time = QTime.currentTime()
        current_date = QDate.currentDate()
        date=current_date.toString(Qt.DefaultLocaleLongDate)
        datetime = QDateTime.currentDateTime()
        day=datetime.toString()[:3]
        hrs=current_time.toString(Qt.DefaultLocaleLongDate)[-2:]
        label_time = current_time.toString('hh:mm:ss')
        self.date.setText(_translate("Mainscreen", date))
        self.Time.setText(_translate("Mainscreen", day+"   "+label_time+" "+hrs))
        self.Register.setText(_translate("Mainscreen", "Register"))
        self.Take_attendance.setText(_translate("Mainscreen", "Take Attendance"))
        self.view_attendance.setText(_translate("Mainscreen", "View Attendance"))
import mainscreen_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Mainscreen = QtWidgets.QMainWindow()
    ui = Ui_Mainscreen()
    ui.setupUi(Mainscreen)
    Mainscreen.show()
    sys.exit(app.exec_())
