# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'splashscreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_splashscreen(object):
    def setupUi(self, splashscreen):
        splashscreen.setObjectName("splashscreen")
        splashscreen.resize(850, 550)
        self.splashmain = QtWidgets.QWidget(splashscreen)
        self.splashmain.setObjectName("splashmain")
        self.BG = QtWidgets.QLabel(self.splashmain)
        self.BG.setGeometry(QtCore.QRect(0, 0, 850, 550))
        self.BG.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(4, 11, 50);")
        self.BG.setText("")
        self.BG.setScaledContents(True)
        self.BG.setObjectName("BG")
        self.Title = QtWidgets.QLabel(self.splashmain)
        self.Title.setEnabled(True)
        self.Title.setGeometry(QtCore.QRect(0, 20, 850, 150))
        self.Title.setStyleSheet("image: url(:/source/cooltext429693349130361.png);")
        self.Title.setText("")
        self.Title.setAlignment(QtCore.Qt.AlignCenter)
        self.Title.setObjectName("Title")
        self.gif = QtWidgets.QLabel(self.splashmain)
        self.gif.setGeometry(QtCore.QRect(213, 160, 425, 310))
        self.gif.setStyleSheet("image: url(:/source/ezgif.com-gif-maker.gif);")
        self.gif.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.gif.setText("")
        self.gif.setAlignment(QtCore.Qt.AlignCenter)
        self.gif.setObjectName("gif")
        self.progressBar = QtWidgets.QProgressBar(self.splashmain)
        self.progressBar.setGeometry(QtCore.QRect(213, 490, 400, 16))
        self.progressBar.setStyleSheet(" QProgressBar{\n"
"background-color: rgb(150, 255, 255);\n"
"color: rgb(0,0,0);\n"
"border-style: none;\n"
"border-radius: 6px;\n"
"text-align : center;\n"
"}\n"
"QProgressBar::chunk{\n"
"border-radius: 6px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.545, x2:1, y2:0.557, stop:0 rgba(0, 0, 255, 255), stop:1 rgba(85, 255, 255, 255));\n"
"    \n"
"}")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setObjectName("progressBar")
        splashscreen.setCentralWidget(self.splashmain)

        self.retranslateUi(splashscreen)
        QtCore.QMetaObject.connectSlotsByName(splashscreen)

    def retranslateUi(self, splashscreen):
        _translate = QtCore.QCoreApplication.translate
        splashscreen.setWindowTitle(_translate("splashscreen", "MainWindow"))
import Splashscreen_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    splashscreen = QtWidgets.QMainWindow()
    ui = Ui_splashscreen()
    ui.setupUi(splashscreen)
    splashscreen.show()
    sys.exit(app.exec_())
